# Generated by Django 3.1 on 2020-08-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_status', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
    ]
