# Generated by Django 3.1 on 2020-08-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('device_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='device_id')),
                ('sensor_name', models.CharField(max_length=30)),
                ('measurement_value', models.CharField(max_length=10)),
            ],
        ),
    ]
